version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "6000:6000"
    container_name: "flask-app"
    volumes:
      - ../src:/app

  db:
    image: mysql:8.0.28
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    #volumes:
      #- ./db:/docker-entrypoint-initdb.d/:ro
    container_name: "flask-db"